### ISSUE TITLE
希望增加360浏览器判断

### ISSUE THREAD

**Issue by SummerHenry** [D-xuanmo/javascript-utils#1]

**Comment by D-xuanmo** [comment]
@SummerHenry 你那里有360浏览器的UA吗？我这边下载Mac和Windows版本，他没有自己的UA标识，而且Mac给的信息也有点问题；
Win：`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36`
Mac：`Mozilla/5.0 (Macintosh; Intel Mac OS X -1_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36`

**Comment by SummerHenry** [comment]
> @SummerHenry 你那里有360浏览器的UA吗？我这边下载Mac和Windows版本，他没有自己的UA标识，而且Mac给的信息也有点问题； Win：`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36` Mac：`Mozilla/5.0 (Macintosh; Intel Mac OS X -1_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36`

我看网上有这样处理的。先判断谷歌，然后如果是谷歌。然后判断mineTypes里是否有“application/vnd.chromium.remoting-viewer” 如果有就是360的。否者就是谷歌
`
 let flag = false;
 var mimeTypes = navigator.mimeTypes
  for (var mt in mimeTypes) {
    if (mimeTypes[mt]['type'] === 'application/vnd.chromium.remoting-viewer') {
      flag = true;
      break;
    }
  }
 if (flag)  {
   // 360
 } 
`

**Comment by D-xuanmo** [comment]
@SummerHenry 目前 ua 解析是解析的 `navigator.userAgent`， 如果按这个方式需要改一下解析才能实现了，这个我看下

> 我看网上有这样处理的。先判断谷歌，然后如果是谷歌。然后判断mineTypes里是否有“application/vnd.chromium.remoting-viewer” 如果有就是360的。否者就是谷歌 `let flag = false; var mimeTypes = navigator.mimeTypes for (var mt in mimeTypes) { if (mimeTypes[mt]['type'] === 'application/vnd.chromium.remoting-viewer') { flag = true; break; } } if (flag) { // 360 } `
